classifier1:
  num_gpus: 0.1
  min_replicas: 1
  initial_replicas: 1
  max_replicas: 4
  target_num_ongoing_requests_per_replica: 8
  graceful_shutdown_timeout_s: 60
  max_batch_size: 8
  batch_wait_timeout_s: 0.5
  
classifier2:
  num_gpus: 0.1
  min_replicas: 1
  initial_replicas: 1
  max_replicas: 4
  target_num_ongoing_requests_per_replica: 8
  graceful_shutdown_timeout_s: 60
  max_batch_size: 8
  batch_wait_timeout_s: 0.5
  
inference:
  min_replicas: 1
  initial_replicas: 1
  max_replicas: 8
  target_num_ongoing_requests_per_replica: 16
  graceful_shutdown_timeout_s: 60
