classifier1:
  num_gpus: 0.05
  min_replicas: 1
  initial_replicas: 10
  max_replicas: 10
  target_num_ongoing_requests_per_replica: 16
  graceful_shutdown_timeout_s: 60
  max_batch_size: 16
  batch_wait_timeout_s: 0.5
  
classifier2:
  num_gpus: 0.05
  min_replicas: 1
  initial_replicas: 10
  max_replicas: 10
  target_num_ongoing_requests_per_replica: 16
  graceful_shutdown_timeout_s: 60
  max_batch_size: 16
  batch_wait_timeout_s: 0.5
  
inference:
  min_replicas: 1
  initial_replicas: 10
  max_replicas: 10
  target_num_ongoing_requests_per_replica: 64
  graceful_shutdown_timeout_s: 60
