# Use an official Ubuntu base image
FROM ubuntu:latest

# Set non-interactive frontend (useful for Docker builds)
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages for both OpenBLAS and Faiss, and SQLite
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    make \
    gfortran \
    python3 \
    python3-pip \
    openssl \
    libssl-dev \
    wget \
    cmake \
    python3-dev \
    python3-numpy \
    swig \
    tzdata \
    tcl \
    fossil \ 
    && rm -rf /var/lib/apt/lists/*

# Clone and install OpenBLAS
WORKDIR /
RUN git clone https://github.com/OpenMathLib/OpenBLAS.git
WORKDIR /OpenBLAS
# install OpenBLAS on a specific path (PREFIX), other custom flags can be added
RUN make
RUN make PREFIX=/usr/local/openblas install
ENV LD_LIBRARY_PATH=/usr/local/openblas/lib:$LD_LIBRARY_PATH

# Install a newer version of CMake for Faiss
WORKDIR /
RUN wget https://github.com/Kitware/CMake/releases/download/v3.23.1/cmake-3.23.1.tar.gz
RUN tar -zxvf cmake-3.23.1.tar.gz
WORKDIR /cmake-3.23.1
RUN ./bootstrap && make && make install

# Set up the environment for Faiss
WORKDIR /faiss
RUN git clone https://github.com/facebookresearch/faiss.git .
# install without GPU support, other custom flags can be added
RUN cmake -B build . -DFAISS_ENABLE_GPU=OFF -DFAISS_ENABLE_PYTHON=ON
RUN make -C build -j $(nproc)
RUN cd build/faiss/python && python3 setup.py install

# Clean up unnecessary files and clear the cache to reduce the image size
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /cmake-3.23.1 /OpenBLAS /faiss

# Set the working directory for the SQLite section
WORKDIR /sqlite

# Preconfigure selected timezone
RUN echo "Europe/Berlin" > /etc/timezone

ENV USER=docker

# Rest of your Dockerfile commands
RUN mkdir -p /sqlite/Fossils \
    && fossil clone https://www.sqlite.org/src /sqlite/Fossils/sqlite.fossil \
    && fossil open --force /sqlite/Fossils/sqlite.fossil

# Configure, make, and install SQLite
RUN ./configure && make && make install

# Clean up unnecessary packages
RUN apt-get remove --purge -y build-essential git make gfortran wget cmake && apt-get autoremove -y

# Set the entry point to the SQLite shell
CMD ["bash"]
